// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eshtcuhyryuhxyuixooo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaHRjdWh5cnl1aHh5dWl4b29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDU2MjQsImV4cCI6MjA1NzIyMTYyNH0.vUtZnEOog-zkr484W_9AXuWnZsoEhsH6yFDKPNrXspw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);